spring.application.name=demoBackend
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/ORCL
spring.datasource.username=C##aritra
spring.datasource.password=Aritra11
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.springframework.jdbc.core.metadata=TRACE

# JPA
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update

# Show generated SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#JWT
jwt.secretkey=JHDFVGBHNJMJIKJH45678998345JHNBCVB76DFCVBN34567
jwt.expiration=36000

#Max File Upload Limit
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

#PICRD Base URL
picrd.base_url=https://picrd.com
